-- Check five tables join and group by
USE DATASET;
SELECT REGION.R_NAME, COUNT(*)
FROM LINEITEM, PARTSUPP, SUPPLIER, NATION, REGION
WHERE LINEITEM.L_PARTKEY = PARTSUPP.PS_PARTKEY 
 AND LINEITEM.L_SUPPKEY = PARTSUPP.PS_SUPPKEY 
 AND PARTSUPP.PS_SUPPKEY = SUPPLIER.S_SUPPKEY 
 AND SUPPLIER.S_NATIONKEY = NATION.N_NATIONKEY
 AND NATION.N_REGIONKEY = REGION.R_REGIONKEY
GROUP BY REGION.R_NAME
;
-- +-------------+----------+
-- | R_NAME      | COUNT(*) |
-- +-------------+----------+
-- | AFRICA      |   349332 |
-- | AMERICA     |   351238 |
-- | ASIA        |   386153 |
-- | EUROPE      |   338359 |
-- | MIDDLE EAST |   375011 |
-- +-------------+----------+
